package com.myspace.evrtic;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Dijete implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Ime Djeteta")
	private java.lang.String imeDjeteta;
	@org.kie.api.definition.type.Label("Prezime djeteta")
	private String prezimeDjeteta;
	@org.kie.api.definition.type.Label("Datum rođenja djeteta")
	private java.util.Date datumRodenjaDjeteta;
	@org.kie.api.definition.type.Label("Spol djeteta")
	private int spolDjeteta;
	@org.kie.api.definition.type.Label("OIB djeteta")
	private java.lang.Long oibDjeteta;
	@org.kie.api.definition.type.Label("Adresa djeteta")
	private java.lang.String adresaDjeteta;

	public Dijete() {
	}

	public java.lang.String getImeDjeteta() {
		return this.imeDjeteta;
	}

	public void setImeDjeteta(java.lang.String imeDjeteta) {
		this.imeDjeteta = imeDjeteta;
	}

	public java.util.Date getDatumRodenjaDjeteta() {
		return this.datumRodenjaDjeteta;
	}

	public void setDatumRodenjaDjeteta(java.util.Date datumRodenjaDjeteta) {
		this.datumRodenjaDjeteta = datumRodenjaDjeteta;
	}

	public int getSpolDjeteta() {
		return this.spolDjeteta;
	}

	public void setSpolDjeteta(int spolDjeteta) {
		this.spolDjeteta = spolDjeteta;
	}

	public java.lang.Long getOibDjeteta() {
		return this.oibDjeteta;
	}

	public void setOibDjeteta(java.lang.Long oibDjeteta) {
		this.oibDjeteta = oibDjeteta;
	}

	public java.lang.String getAdresaDjeteta() {
		return this.adresaDjeteta;
	}

	public void setAdresaDjeteta(java.lang.String adresaDjeteta) {
		this.adresaDjeteta = adresaDjeteta;
	}

	public java.lang.String getPrezimeDjeteta() {
		return this.prezimeDjeteta;
	}

	public void setPrezimeDjeteta(java.lang.String prezimeDjeteta) {
		this.prezimeDjeteta = prezimeDjeteta;
	}

	public Dijete(java.lang.String imeDjeteta, java.lang.String prezimeDjeteta,
			java.util.Date datumRodenjaDjeteta, int spolDjeteta,
			java.lang.Long oibDjeteta, java.lang.String adresaDjeteta) {
		this.imeDjeteta = imeDjeteta;
		this.prezimeDjeteta = prezimeDjeteta;
		this.datumRodenjaDjeteta = datumRodenjaDjeteta;
		this.spolDjeteta = spolDjeteta;
		this.oibDjeteta = oibDjeteta;
		this.adresaDjeteta = adresaDjeteta;
	}

}