package com.myspace.evrtic;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Dokument implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Opis dokumenta")
	private String opisDokumenta;

	@org.kie.api.definition.type.Label("Bodovi dokumenta")
	private int bodoviDokumenta;

	@org.kie.api.definition.type.Label(value = "Prilozio")
	private java.lang.Boolean prilozio;

	public Dokument() {
	}

	public java.lang.String getOpisDokumenta() {
		return this.opisDokumenta;
	}

	public void setOpisDokumenta(java.lang.String opisDokumenta) {
		this.opisDokumenta = opisDokumenta;
	}

	public int getBodoviDokumenta() {
		return this.bodoviDokumenta;
	}

	public void setBodoviDokumenta(int bodoviDokumenta) {
		this.bodoviDokumenta = bodoviDokumenta;
	}

	public java.lang.Boolean getPrilozio() {
		return this.prilozio;
	}

	public void setPrilozio(java.lang.Boolean prilozio) {
		this.prilozio = prilozio;
	}

	public Dokument(java.lang.String opisDokumenta, int bodoviDokumenta,
			java.lang.Boolean prilozio) {
		this.opisDokumenta = opisDokumenta;
		this.bodoviDokumenta = bodoviDokumenta;
		this.prilozio = prilozio;
	}

}