package com.myspace.evrtic;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PodaciZahtjeva implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Lista dokumenata")
	private java.util.List<com.myspace.evrtic.Dokument> listaDokumenata;
	@org.kie.api.definition.type.Label("Zahtjev za upis")
	private com.myspace.evrtic.ZahtjevZaUpis zahtjevZaUpis;

	@org.kie.api.definition.type.Label("Ukupan broj bodova")
	private int ukupanBrojBodova;

	public PodaciZahtjeva() {
	}

	public java.util.List<com.myspace.evrtic.Dokument> getListaDokumenata() {
		return this.listaDokumenata;
	}

	public void setListaDokumenata(
			java.util.List<com.myspace.evrtic.Dokument> listaDokumenata) {
		this.listaDokumenata = listaDokumenata;
	}

	public com.myspace.evrtic.ZahtjevZaUpis getZahtjevZaUpis() {
		return this.zahtjevZaUpis;
	}

	public void setZahtjevZaUpis(com.myspace.evrtic.ZahtjevZaUpis zahtjevZaUpis) {
		this.zahtjevZaUpis = zahtjevZaUpis;
	}

	public int getUkupanBrojBodova() {
		return this.ukupanBrojBodova;
	}

	public void setUkupanBrojBodova(int ukupanBrojBodova) {
		this.ukupanBrojBodova = ukupanBrojBodova;
	}

	public PodaciZahtjeva(
			java.util.List<com.myspace.evrtic.Dokument> listaDokumenata,
			com.myspace.evrtic.ZahtjevZaUpis zahtjevZaUpis, int ukupanBrojBodova) {
		this.listaDokumenata = listaDokumenata;
		this.zahtjevZaUpis = zahtjevZaUpis;
		this.ukupanBrojBodova = ukupanBrojBodova;
	}

}