package com.myspace.evrtic;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PodaciZahtjeva implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "ID podataka zahtjeva")
	private int idPodatakaZahtjeva;
	@org.kie.api.definition.type.Label(value = "Lista dokumenata")
	private java.util.List<com.myspace.evrtic.Dokument> listaDokumenata;
	@org.kie.api.definition.type.Label(value = "Zahtjev za upis")
	private com.myspace.evrtic.ZahtjevZaUpis zahtjevZaUpis;

	public PodaciZahtjeva() {
	}

	public int getIdPodatakaZahtjeva() {
		return this.idPodatakaZahtjeva;
	}

	public void setIdPodatakaZahtjeva(int idPodatakaZahtjeva) {
		this.idPodatakaZahtjeva = idPodatakaZahtjeva;
	}

	public java.util.List<com.myspace.evrtic.Dokument> getListaDokumenata() {
		return this.listaDokumenata;
	}

	public void setListaDokumenata(
			java.util.List<com.myspace.evrtic.Dokument> listaDokumenata) {
		this.listaDokumenata = listaDokumenata;
	}

	public com.myspace.evrtic.ZahtjevZaUpis getZahtjevZaUpis() {
		return this.zahtjevZaUpis;
	}

	public void setZahtjevZaUpis(com.myspace.evrtic.ZahtjevZaUpis zahtjevZaUpis) {
		this.zahtjevZaUpis = zahtjevZaUpis;
	}

	public PodaciZahtjeva(int idPodatakaZahtjeva,
			java.util.List<com.myspace.evrtic.Dokument> listaDokumenata,
			com.myspace.evrtic.ZahtjevZaUpis zahtjevZaUpis) {
		this.idPodatakaZahtjeva = idPodatakaZahtjeva;
		this.listaDokumenata = listaDokumenata;
		this.zahtjevZaUpis = zahtjevZaUpis;
	}

}