package com.myspace.evrtic;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RangLista implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Kvota")
	private int kvota;

	public RangLista() {
	}

	public int getKvota() {
		return this.kvota;
	}

	public void setKvota(int kvota) {
		this.kvota = kvota;
	}

	public RangLista(int kvota) {
		this.kvota = kvota;
	}

}