package com.myspace.evrtic;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RangLista implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Id rang liste")
	private int idRangListe;
	@org.kie.api.definition.type.Label("Kvota")
	private int kvota;

	@org.kie.api.definition.type.Label("Podaci zahtjeva")
	private com.myspace.evrtic.PodaciZahtjeva podaciZahtjeva;

	public RangLista() {
	}

	public int getIdRangListe() {
		return this.idRangListe;
	}

	public void setIdRangListe(int idRangListe) {
		this.idRangListe = idRangListe;
	}

	public int getKvota() {
		return this.kvota;
	}

	public void setKvota(int kvota) {
		this.kvota = kvota;
	}

	public com.myspace.evrtic.PodaciZahtjeva getPodaciZahtjeva() {
		return this.podaciZahtjeva;
	}

	public void setPodaciZahtjeva(
			com.myspace.evrtic.PodaciZahtjeva podaciZahtjeva) {
		this.podaciZahtjeva = podaciZahtjeva;
	}

	public RangLista(int idRangListe, int kvota,
			com.myspace.evrtic.PodaciZahtjeva podaciZahtjeva) {
		this.idRangListe = idRangListe;
		this.kvota = kvota;
		this.podaciZahtjeva = podaciZahtjeva;
	}

}