package com.myspace.evrtic;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Roditelj implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Ime majke")
	private java.lang.String imeMajke;
	@org.kie.api.definition.type.Label("Prezime majke")
	private java.lang.String prezimeMajke;
	@org.kie.api.definition.type.Label("Majka zaposlena")
	private java.lang.Boolean majkaZaposlena;
	@org.kie.api.definition.type.Label("OIB majke")
	private java.lang.Long oibMajke;
	@org.kie.api.definition.type.Label("Ime oca")
	private java.lang.String imeOca;
	@org.kie.api.definition.type.Label("Prezime oca")
	private java.lang.String prezimeOca;
	@org.kie.api.definition.type.Label("Otac zaposlen")
	private java.lang.Boolean otacZaposlen;
	@org.kie.api.definition.type.Label("OIB oca")
	private java.lang.Long oibOca;

	public Roditelj() {
	}

	public java.lang.String getImeMajke() {
		return this.imeMajke;
	}

	public void setImeMajke(java.lang.String imeMajke) {
		this.imeMajke = imeMajke;
	}

	public java.lang.String getPrezimeMajke() {
		return this.prezimeMajke;
	}

	public void setPrezimeMajke(java.lang.String prezimeMajke) {
		this.prezimeMajke = prezimeMajke;
	}

	public java.lang.Boolean getMajkaZaposlena() {
		return this.majkaZaposlena;
	}

	public void setMajkaZaposlena(java.lang.Boolean majkaZaposlena) {
		this.majkaZaposlena = majkaZaposlena;
	}

	public java.lang.Long getOibMajke() {
		return this.oibMajke;
	}

	public void setOibMajke(java.lang.Long oibMajke) {
		this.oibMajke = oibMajke;
	}

	public java.lang.String getImeOca() {
		return this.imeOca;
	}

	public void setImeOca(java.lang.String imeOca) {
		this.imeOca = imeOca;
	}

	public java.lang.String getPrezimeOca() {
		return this.prezimeOca;
	}

	public void setPrezimeOca(java.lang.String prezimeOca) {
		this.prezimeOca = prezimeOca;
	}

	public java.lang.Boolean getOtacZaposlen() {
		return this.otacZaposlen;
	}

	public void setOtacZaposlen(java.lang.Boolean otacZaposlen) {
		this.otacZaposlen = otacZaposlen;
	}

	public java.lang.Long getOibOca() {
		return this.oibOca;
	}

	public void setOibOca(java.lang.Long oibOca) {
		this.oibOca = oibOca;
	}

	public Roditelj(java.lang.String imeMajke, java.lang.String prezimeMajke,
			java.lang.Boolean majkaZaposlena, java.lang.Long oibMajke,
			java.lang.String imeOca, java.lang.String prezimeOca,
			java.lang.Boolean otacZaposlen, java.lang.Long oibOca) {
		this.imeMajke = imeMajke;
		this.prezimeMajke = prezimeMajke;
		this.majkaZaposlena = majkaZaposlena;
		this.oibMajke = oibMajke;
		this.imeOca = imeOca;
		this.prezimeOca = prezimeOca;
		this.otacZaposlen = otacZaposlen;
		this.oibOca = oibOca;
	}

}