package com.myspace.evrtic;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Ugovor implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "ID ugovora")
	private int idUgovora;
	@org.kie.api.definition.type.Label(value = "Podaci zahtjeva")
	private com.myspace.evrtic.PodaciZahtjeva podaciZahtjeva;
	@org.kie.api.definition.type.Label(value = "Potpis ravnateljice")
	private java.lang.String potpisRavnateljice;
	@org.kie.api.definition.type.Label(value = "Potpis roditelja")
	private java.lang.String potpisRoditelja;
	@org.kie.api.definition.type.Label(value = "Datum ugovora")
	private java.util.Date datumUgovora;

	public Ugovor() {
	}

	public int getIdUgovora() {
		return this.idUgovora;
	}

	public void setIdUgovora(int idUgovora) {
		this.idUgovora = idUgovora;
	}

	public com.myspace.evrtic.PodaciZahtjeva getPodaciZahtjeva() {
		return this.podaciZahtjeva;
	}

	public void setPodaciZahtjeva(
			com.myspace.evrtic.PodaciZahtjeva podaciZahtjeva) {
		this.podaciZahtjeva = podaciZahtjeva;
	}

	public java.lang.String getPotpisRavnateljice() {
		return this.potpisRavnateljice;
	}

	public void setPotpisRavnateljice(java.lang.String potpisRavnateljice) {
		this.potpisRavnateljice = potpisRavnateljice;
	}

	public java.lang.String getPotpisRoditelja() {
		return this.potpisRoditelja;
	}

	public void setPotpisRoditelja(java.lang.String potpisRoditelja) {
		this.potpisRoditelja = potpisRoditelja;
	}

	public java.util.Date getDatumUgovora() {
		return this.datumUgovora;
	}

	public void setDatumUgovora(java.util.Date datumUgovora) {
		this.datumUgovora = datumUgovora;
	}

	public Ugovor(int idUgovora,
			com.myspace.evrtic.PodaciZahtjeva podaciZahtjeva,
			java.lang.String potpisRavnateljice,
			java.lang.String potpisRoditelja, java.util.Date datumUgovora) {
		this.idUgovora = idUgovora;
		this.podaciZahtjeva = podaciZahtjeva;
		this.potpisRavnateljice = potpisRavnateljice;
		this.potpisRoditelja = potpisRoditelja;
		this.datumUgovora = datumUgovora;
	}

}