package com.myspace.evrtic;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ZahtjevZaUpis implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Odabrani vrtić")
	private java.lang.String odabraniVrtic;
	@org.kie.api.definition.type.Label("Odabrani program")
	private java.lang.String odabraniProgram;
	@org.kie.api.definition.type.Label("Datum slanja zahtjeva za upis")
	private java.util.Date datumSlanjaZahtjevaZaUpis;

	@org.kie.api.definition.type.Label("Dijete")
	private com.myspace.evrtic.Dijete dijete;

	@org.kie.api.definition.type.Label("Roditelj")
	private com.myspace.evrtic.Roditelj roditelj;

	public ZahtjevZaUpis() {
	}

	public java.lang.String getOdabraniVrtic() {
		return this.odabraniVrtic;
	}

	public void setOdabraniVrtic(java.lang.String odabraniVrtic) {
		this.odabraniVrtic = odabraniVrtic;
	}

	public java.lang.String getOdabraniProgram() {
		return this.odabraniProgram;
	}

	public void setOdabraniProgram(java.lang.String odabraniProgram) {
		this.odabraniProgram = odabraniProgram;
	}

	public java.util.Date getDatumSlanjaZahtjevaZaUpis() {
		return this.datumSlanjaZahtjevaZaUpis;
	}

	public void setDatumSlanjaZahtjevaZaUpis(
			java.util.Date datumSlanjaZahtjevaZaUpis) {
		this.datumSlanjaZahtjevaZaUpis = datumSlanjaZahtjevaZaUpis;
	}

	public com.myspace.evrtic.Dijete getDijete() {
		return this.dijete;
	}

	public void setDijete(com.myspace.evrtic.Dijete dijete) {
		this.dijete = dijete;
	}

	public com.myspace.evrtic.Roditelj getRoditelj() {
		return this.roditelj;
	}

	public void setRoditelj(com.myspace.evrtic.Roditelj roditelj) {
		this.roditelj = roditelj;
	}

	public ZahtjevZaUpis(java.lang.String odabraniVrtic,
			java.lang.String odabraniProgram,
			java.util.Date datumSlanjaZahtjevaZaUpis,
			com.myspace.evrtic.Dijete dijete,
			com.myspace.evrtic.Roditelj roditelj) {
		this.odabraniVrtic = odabraniVrtic;
		this.odabraniProgram = odabraniProgram;
		this.datumSlanjaZahtjevaZaUpis = datumSlanjaZahtjevaZaUpis;
		this.dijete = dijete;
		this.roditelj = roditelj;
	}

}